:sourcedir: .
:last-update-label!:
:source-highlighter: coderay
:icons: font
= Markable - API Reference
Reference
:toclevels: 3
:toc: left
:toc-title:

[reference]
== Reference

```c++
namespace ak_toolkit
{
  namespace markable_ns
  {
    template <typename MP, template <typename, typename> class OP = order_none>
      class markable;

    void swap(markable & l, markable & r);

    template <typename T, typename NT = T, typename CREF = const T&, typename REPT = NT>
      struct markable_type;

    template <typename MP>
      struct dual_storage;

    template <typename MP>
      void swap(dual_storage & l, dual_storage & r);

    template <typename MPT, typename T, typename DUAL_T>
      struct markable_dual_storage_type;

    template <typename MPT, typename T, typename DUAL_T>
      struct markable_dual_storage_type_unsafe;

    template <typename T, T Val>
      struct mark_int;

    template <typename FPT>
      struct mark_fp_nan;

    template <typename T>
      struct mark_value_init;

    template <typename T>
      struct mark_stl_empty;

    template <typename OT>
      struct mark_optional;

    struct mark_bool;

    template <typename Enum, std::underlying_type_t<Enum> Val>
      struct mark_enum;

    template <typename T>
      struct representation_of;

    template <typename Markable>
      class order_none;

    template <typename Markable>
      class order_by_representation;

    template <typename Markable>
      class order_by_value;

    template <typename T>
      using default_markable = /* see below */;
  }

  using markable_ns::markable;
  using markable_ns::markable_type;
  using markable_ns::markable_dual_storage_type;
  using markable_ns::markable_dual_storage_type_unsafe;
  using markable_ns::mark_bool;
  using markable_ns::mark_int;
  using markable_ns::mark_fp_nan;
  using markable_ns::mark_value_init;
  using markable_ns::mark_optional;
  using markable_ns::mark_stl_empty;
  using markable_ns::mark_enum;
  using markable_ns::order_none;
  using markable_ns::order_by_representation;
  using markable_ns::order_by_value;
  using markable_ns::default_markable;
}
```

[concept_mark_policy]
== Concept `mark_policy`

```c++
template <typename MP>
concept mark_policy =
  requires
  {
    typename MP::value_type;
    typename MP::storage_type;
    typename MP::reference_type;
    typename MP::representation_type;
  } &&
  requires(const typename MP::representation_type &  cr,
                 typename MP::representation_type && rr,
           const typename MP::storage_type &         s,
           const typename MP::value_type &           cv,
                 typename MP::value_type &&          rv)
  {
    { MP::marked_value() }                      -> std::convertible_to<typename MP::representation_type>;
    { MP::is_marked_value(cr) }                 -> std::convertible_to<bool>;

    { MP::access_value(s) }                     -> std::same_as<typename MP::reference_type>;
    { MP::representation(s) }                   -> std::same_as<const typename MP::representation_type &>;
    { MP::store_value(cv) }                     -> std::convertible_to<typename MP::storage_type>;
    { MP::store_value(std::move(rv)) }          -> std::convertible_to<typename MP::storage_type>;
    { MP::store_representation(cr) }            -> std::convertible_to<typename MP::storage_type>;
    { MP::store_representation(std::move(rr)) } -> std::convertible_to<typename MP::storage_type>;
  };
```


#### `value_type`
This represents the type 'logically' stored by the markable object. Markable object tries to make an impression on the users that it is internally storing an objectof type `value_type`, which is often the case, but not always.

#### `storage_type`
This represents the type of the sub-object physically stored inside markable object, which is used to store the value of the object as well as the empty-state mark.

#### `reference_type`
This represents the type returned when the user requests read access to the stored value. Typically, this type is defined as `const value_type&`, however, sometimes when the accessed value is computed on the fly, this type may be defined as `value_type`.

#### `representation_type`
It is in this type that the special marked value is encoded. Typically, this is `storage_type`, but in some cases `storage_type` neds to be cast to this type.

#### `{ marked_value() } -> std::convertible_to<typename MP::representation_type>`
Returns a marked value encoded in `representation_type`. This will be later used to represent a markable object with no value.

#### `{ is_marked_value(r) } -> std::convertible_to<bool>`
Checks if the given value represents a marked value.

#### `{ access_value(s) } -> std::same_as<typename MP::reference_type>`
*Preconditions:* `!is_marked_value(s)`.

Given a value encoded in `storage_type`, provides access to it through type `reference_type`. Typically, when `reference_type` and `const storage_type&` are same type, this is an identity function.

#### `{ representation(s) }  -> std::same_as<const typename MP::representation_type &>`

Performs adjustments (if necessary) to represent the stored object through `representation_type`.

#### `{ store_value(v) } -> std::convertible_to<typename MP::storage_type>`
Given a value of type `value_type` (possibly marked), returns its representation as `storage_type`. Typically, when `value_type` and `storage_type` are same type, this is an identity function.

#### `{ store_representation(r) } -> std::convertible_to<typename MP::storage_type>`
Given a value of type `representation_type`, returns its representation as `storage_type`. Typically, when `representation_type` and `storage_type` are same type, this is an identity function.

## Class template `markable`

```c++
namespace ak_toolkit
{
  namespace markable_ns
  {
    template <mark_policy MP, template <typename> class OP = order_none>
    class markable
    {
    public:
      typedef typename MP::value_type           value_type;
      typedef typename MP::representation_type  representation_type;
      typedef typename MP::reference_type       reference_type;

      constexpr markable() noexcept(noexcept(storage_type{MP::marked_value{}}));
      constexpr explicit markable(const value_type& v);
      constexpr explicit markable(value_type&& v);
      constexpr markable(const markable&) = default;
      constexpr markable(markable&&) = default;

      constexpr markable& operator=(const markable&) = default;
      constexpr markable& operator=(markable&&) = default;

      constexpr bool has_value() const;
      constexpr reference_type value() const;
      constexpr representation_type const& representation_value() const;

      void assign(value_type&& v);
      void assign(const value_type& v);

      void assign_representation(representation_type&& s);
      void assign_representation(representation_type const& s);

    private:
      typename MP::storage_type val_; // exposition only
    };
  }
}
```

#### `markable()`

*Effects:* Initializes storage value with expression `MP::marked_value()`.

*Postconditions:* `!has_value()`.

#### `markable(const value_type& v)`

*Effects:* Initializes storage value with expression `MP::store_value(v)`.

*Postconditions:* `has_value() == !MP::is_marked_value(v)`.

#### `markable(value_type&& v)`

*Effects:* Initializes storage value with expression `MP::store_value(std::move(v))`.

*Postconditions:* `has_value() == !MP::is_marked_value(v)`.

#### `reference_type has_value() const`

*Returns:* `!MP::is_marked_value(val_)`.

*Throws:* Nothing.


#### `reference_type value() const`

*Preconditions:* `has_value()`.

*Returns:* `MP::access_value(val_)`.

*Throws:* Whatever `MP::access_value` throws. Also, if `reference_type` is in fact not a reference type, whatever `reference_type`'s move constructor throws.


#### `representation_type const& representation_value() const`

*Returns:* `MP::representation(val_)`.

*Throws:* Nothing.


#### `void assign(const value_type& v)`

*Effects:* Assigns storage value with expression `MP::store_value(v)`.

*Postconditions:* `has_value() == !MP::is_marked_value(v)`.

*Remarks:*  If an exception is thrown during the call to `storage_type`'s assignment,
 the state of `val_`  is determined by the exception safety guarantee of `storage_type`’s
 assignment.


#### `void assign(value_type&& v)`

*Effects:* Assigns storage value with expression `MP::store_value(std::move(v))`.

*Postconditions:* `has_value() == !MP::is_marked_value(v)`.

*Remarks:*  If an exception is thrown during the call to `storage_type`'s assignment,
 the state of `val_` is determined by the exception safety guarantee of `storage_type`’s
 assignment.


#### `void assign_representation(const representation_type& v)`

*Effects:* Assigns storage value with expression `v`.

*Postconditions:* `has_value() == !MP::is_marked_value(MP::representation(v))`.

*Remarks:*  If an exception is thrown during the call to `storage_type`'s assignment,
 the state of `val_`  is determined by the exception safety guarantee of `storage_type`’s
 assignment.


#### `void assign_representation(representation_type&& v)`

*Effects:* Assigns storage value with expression `std::move(v)`.

*Postconditions:* `has_value() == !MP::is_marked_value(MP::representation(v))`.

*Remarks:*  If an exception is thrown during the call to `storage_type`'s assignment,
 the state of `val_` is determined by the exception safety guarantee of `storage_type`’s
 assignment.


### Relational operators

Whether `markable` provides the six relational operations as well as `std::hash`
specializations depends on ordering policy `OP`. This library comes with three
policies:

#### `order_none`

No relational operators are provided. No `std::hash` specialization is provided.


#### `order_by_value`

Given two `markable`s `m1` and `m2` of type `markable<MP, order_by_value>`:

`m1 == m2` is equivalent to `!m1.has_value() ? !m2.has_value() : m2.has_value() && m1.value() == m2.value()`.

`m1 < m2` is equivalent to `!m2.has_value() ? false : (!m1.has_value() ? true : m1.value() < m2.value())`.


#### `order_by_representation`

Given two `markable`s `m1` and `m2` of type `markable<MP, order_by_representation>`:

`m1 == m2` is equivalent to `m1.representation_value() == !m2.representation_value()`.

`m1 < m2` is equivalent to `m1.representation_value() < !m2.representation_value()`.

*Remark:* If `m1` or `m2` (called `m` here) stores a value where
`!m.has_value() && m.representation_value() != MP::marked_value()`
the behavior is undefined.


### Exception safety

If an exception is thrown during the assignment,
the state of `*this` depends on the exception safety guarantees of the assignment in
`storage_type`. If `storage_type`'s assignment offers a weak guarantee,
 the corresponding `markable<>` type also offers only a weak guarantee in assignment.
 In particular, the value of `has_value()` may change.



## Mark policy creation tools

The following tools help build custom mark policies.


### Class template `markable_type`

This class template provides default definitions form most of the requirements in concept `mark_policy`. When declaring your own mark policy, you probably want to derive from this class template (although it is not strictly necessary).

```c++
template <typename T, typename STORE = T, typename CREF = const T&, typename REPT = NT>
struct markable_type
{
  typedef T     value_type;
  typedef STORE storage_type;
  typedef CREF  reference_type;
  typedef REPT  representation_type;

  static constexpr reference_type access_value(const storage_type& v) { return v; }
  static constexpr const representation_type& representation(const storage_type& v) { return v; }
  static constexpr const value_type& store_value(const value_type& v) { return v; }
  static constexpr value_type&& store_value(value_type&& v) { return std::move(v); }
  static constexpr storage_type&& store_representation(const representation_type& v) { return v; }
  static constexpr storage_type&& store_representation(representation_type&& v) { return std::move(v); }
  };
};
```

### Class template `markable_dual_storage_type`

You typically want to derive from this type when defining a mark policy for dual storage. This class template provides default definitions form most of the requirements in concept `mark_policy`. `MPT` is the type of the policy you are defining (we are using the CRTP). `T` is the `value_type` you want to logically represent. `DUAL_T` is a type layout compatible with `T` but with weaker invariants, so that it can store more valid states than `T`.

```c++
template <typename MPT, typename T, typename DUAL_T>
struct markable_dual_storage_type
{
  typedef T                 value_type;
  typedef DUAL_T            representation_type;
  typedef const T&          reference_type;
  typedef dual_storage<MPT> storage_type;

  static reference_type access_value(const storage_type& v) { return v.as_value_type(); }
  static const representation_type& representation(const storage_type& v) { return v.representation(); }
  static storage_type store_value(const value_type& v) { return storage_type(v); }
  static storage_type store_value(value_type&& v) { return storage_type(std::move(v)); }
};
```

*Requires:* `MPT` is a model of `mark_policy`; `T` and `DUAL_T` are layout-compatible types; `std::is_nothrow_move_constructible<DUAL_T>::value is `true`; `noexcept(MPT::marked_value())` is `true`.

### Class template `markable_dual_storage_type_unsafe`

Its semantics and usage are the same as in `markable_dual_storage_type` except for the relaxed requirements.

*Requires:* `MPT` is a model of `mark_policy`; `T` and `DUAL_T` are layout-compatible types;

### Class template `dual_storage`

Class used to store inside a union members of type `value_type` and `representation_type`, and manage them appropriately.

```c++
template <typename MP>
struct dual_storage
{
  typedef typename MP::value_type value_type;
  typedef typename MP::representation_type representation_type;
  typedef typename MP::reference_type reference_type;

  bool has_value() const noexcept;
  value_type&        as_value();
  const value_type&  as_value() const;
  representation_type&       representation()       noexcept;
  const representation_type& representation() const noexcept;

  constexpr explicit dual_storage(representation_type&& mv) noexcept(/*see below*/);
  constexpr explicit dual_storage(const value_type& v);
  constexpr explicit dual_storage(value_type&& v) noexcept(/*see below*/);
  dual_storage(const dual_storage& rhs);
  dual_storage(dual_storage&& rhs) noexcept(/*see below*/);
  void operator=(const dual_storage& rhs);
  void operator=(dual_storage&& rhs) noexcept(/*see below*/);
  friend void swap(dual_storage& lhs, dual_storage& rhs) noexcept(/*see below*/);
  ~dual_storage();
};
```

An object of class `dual_storage` contains a union of two members of types `value_type` and `representation_type`.
Such object is said to _have value_ if its active member is of type `value_type`.
Types `value_type` and `representation_type` shall be layout-compatible.

For an object of class `dual_storage` that does not have a value, to _change to value with expression_ `v` means the following sequence of instructions:

1. An active member of type `representation_type` is destroyed.
2. A member of type `value_type` is activated by the non-brace initialization with expression `v`.

If this initialization exits via an exception `e`, an attempt is made to activate the member of type `representation_type` through non-brace initialization with expression `MP::marked_value()`. If the latter initialization exits via an exception, `std::teriminate()` is called, otherwise the exception `e` is rethrown.

For an object of type `dual_storage` that has a value, to _clear the value_ means the following sequence of instructions:

1. An active member of type `value_type` is destroyed.
2. A member of type `representation_type` is activated through non-brace initialization with expression `MP::marked_value()`. If the latter initialization exits via an exception `e`, `std::teriminate()` is called, otherwise the exception `e` is rethrown.

#### `bool has_value() const noexcept;`
*Returns:* `!MP::is_marked_value(representation())`.

*Remarks:* This tests if the object has value.


#### `value_type&        as_value();`
#### `const value_type&  as_value() const;`
*Preconditions:* `has_value() == true`.

*Returns:* a reference to the active union member of type `value_type`.

#### `representation_type&       representation()       noexcept;`
#### `const representation_type& representation() const noexcept;`

*Effects:* if `has_value() == false` returns a reference to the active union member of type `representation_type`;
otherwise accesses the inactive union member `representation_type` and throug common initial sequence accesses the value of active member `value_type` and returns thus obtained reference.


#### `constexpr explicit dual_storage(representation_type&& mv) noexcept(/\*see below*/);`

*Effects:* Direct-non-list-initializes the union member of type `representation_type` with expression `std::move(mv)`.

*Postcondition:* `has_value() == !MP::is_marked_value(mv)`.

*Remarks:* The expression inside `noexcept` is equivalent to `std::is_nothrow_move_constructible_v<representation_type>`.


#### `constexpr explicit dual_storage(const value_type& v);`

*Effects:* Direct-non-list-initializes the union member of type `value_type` with expression `v`.

*Postcondition:* `has_value() == !MP::is_marked_value(representation())`.


#### `constexpr explicit dual_storage(value_type&& v) noexcept(/\*see below*/);`

*Effects:* Direct-non-list-initializes the union member of type `value_type` with expression `std::move(v)`.

*Postcondition:* `has_value() == !MP::is_marked_value(representation())`.

*Remarks:* The expression inside `noexcept` is equivalent to `std::is_nothrow_move_constructible_v<value_type>`.


#### `dual_storage(const dual_storage& rhs);`

*Requires:* `std::is_copy_constructible_v<value_type>` is `true` and `std::is_copy_constructible_v<representation_type>` is `true`.

*Effects:* If `rhs` has a value, activates the union member of type `value_type` as if direct-non-list-initializing an object
of type `value_type` with the expression `rhs.as_value()`; otherwise activates the union member of type `representation_type` as if direct-non-list-initializing an object of type `representation_type` with the expression `MP::mared_value()`.

*Postcondition:* `rhs.has_value() == this->has_value()`.

*Throws:* Any exception thrown during the initialization of the union member.


#### `dual_storage( dual_storage&& rhs) noexcept(/\*see below*/);`

*Requires:* `std::is_copy_constructible_v<value_type>` is `true` and `std::is_copy_constructible_v<representation_type>` is `true`.

*Effects:* If `rhs` has a value, activates the union member of type `value_type` as if direct-non-list-initializing an object
of type `value_type` with the expression `std::move(rhs.as_value())`; otherwise activates the union member of type `representation_type` as if direct-non-list-initializing an object of type `representation_type` with the expression `MP::mared_value()`.

*Postcondition:* `rhs.has_value() == this->has_value()`.

*Throws:* Any exception thrown during the initialization of the union member.

*Remarks:* The expression inside `noexcept` is equivalent to `std::is_nothrow_move_constructible_v<value_type> && std::is_nothrow_move_constructible_v<representation_type>`.

#### `friend void swap(dual_storage& lhs, dual_storage& rhs) noexcept(/\*see below*/);`

*Effects:*
|===
|  |  `lhs.has_value()` | `!lhs.has_value()`

| `rhs.has_value()`
| calls `swap(lhs.as_value(), rhs.as_value())` (ADL also searches in `std`)
| `lhs` changes value to `std::move(rhs.as_value())`; the value of `rhs` is cleared; if an exception is thrown the values of `lhs` and `rhs` remain unchanged

| `!rhs.has_value()`
| `rhs` changes value to `std::move(lhs.as_value())`; the value of `lhs` is cleared; if an exception is thrown the values of `lhs` and `rhs` remain unchanged
| no effect
|===

*Throws:* Whatever is thrown by operations `swap(lhs.as_value(), rhs.as_value())` (where ADL also searches in `std`) and `value_type(std::move(rhs.as_value()))`.

*Remarks:* The expression inside `noexcept` is equivalent to `std::is_nothrow_swappable_v<value_type> && std::is_nothrow_move_constructible_v<value_type>`.


#### `void operator=(dual_storage&& rhs) noexcept(/\*see below*/);`

*Effects:*
|===
|  |  `has_value()` | `!has_value()`

| `rhs.has_value()`
| calls `as_value() = std::move(rhs.as_value())`
| `*this` changes value to `std::move(rhs.as_value())`

| `!rhs.has_value()`
| the value of `*this` is cleared
| no effect
|===

*Throws:* Whatever is thrown by operations `lhs.as_value() = std::move(rhs.as_value())` and `value_type(std::move(rhs.as_value()))`.

*Remarks:* The expression inside `noexcept` is equivalent to `std::is_nothrow_move_assignable_v<value_type> && std::is_nothrow_move_constructible_v<value_type>`.


#### `void operator=(const dual_storage&& rhs);`

*Effects:*
|===
|  |  `has_value()` | `!has_value()`

| `rhs.has_value()`
| calls `as_value() = rhs.as_value()`
| `*this` changes value to `rhs.as_value()`

| `!rhs.has_value()`
| the value of `*this` is cleared
| no effect
|===

*Throws:* Whatever is thrown by operations `lhs.as_value() = rhs.as_value()` and `value_type(rhs.as_value())`.

#### `~dual_storage();`
*Effects:* if `has_value() == true`, destroys the active member of type `value_type`, otherwise destroys the active member of `representation_type`.


## Predefined mark policies


### Class template `mark_int`

```c++
template <typename Integral, Integral MVal>
struct mark_int : markable_type<T>
{
  static constexpr Integral marked_value() noexcept { return MVal; }
  static constexpr bool is_marked_value(Integral v) { return v == MVal; }
};
```

`Integral` represents the stored type. It can be any type suitable for non-type template parameter.

`EV` is the value the empty value representation.

### Class template `mark_fp_nan`

```c++
template <typename FPT>
  requires std::is_floating_point<FPT>::value
        && std::numeric_limits<FPT>::has_quiet_NaN
struct mark_fp_nan : markable_type<FPT>
{
  static constexpr FPT marked_value() noexcept { return std::numeric_limits<FPT>::quiet_NaN(); }
  static constexpr bool is_marked_value(FPT v) { return v != v; }
};
```

### Class template `mark_value_init`

```c++
template <typename T>
struct mark_value_init : markable_type<T>
{
  static constexpr T marked_value() noexcept(see below) { return T{}; }
  static constexpr bool is_marked_value(const T& v) { return v == T{}; }
};
```

`T` is required to be a regular type.

The expression inside `noexcept` should be equivalent to `std::is_nothrow_default_constructible<T>::value && std::is_nothrow_move_constructible<T>::value`.

### Class template `mark_stl_empty`

```c++
template <typename Cont>
struct mark_stl_empty : markable_type<Cont>
{
  static constexpr Cont marked_value() noexcept(see below) { return Cont{}; }
  static constexpr bool is_marked_value(const Cont& v) { return v.empty(); }
};
```

`Cont` is required to be a container in the STL sense.

The expression inside `noexcept` should be equivalent to `std::is_nothrow_default_constructible<Cont>::value && std::is_nothrow_move_constructible<Cont>::value`.

### Class template `mark_optional`

```c++
template <typename OT>
struct mark_optional : markable_type<typename OT::value_type, OT>
{
  typedef typename OT::value_type value_type;
  typedef OT storage_type;

  static OT marked_value() noexcept { return OT{}; }
  static bool is_marked_value(const OT& v) { return !v; }

  static const value_type& access_value(const storage_type& v) { return *v; }
  static storage_type store_value(const value_type& v) { return v; }
  static storage_type store_value(value_type&& v) { return std::move(v); }
};
```

`OT` is required to be either `boost::optional` or `std::experimental::optional` or `std::optional` or a type sufficiently similar to these.

### Class template `mark_bool`

```c++
struct mark_bool : markable_type<bool, char, bool>
{
  static constexpr char marked_value() noexcept { return char(2); }
  static constexpr bool is_marked_value(char v) { return v == 2; }

  static constexpr bool access_value(const char& v) { return bool(v); }
  static constexpr char store_value(const bool& v) { return v; }
};
```

### Class template `mark_enum`

```c++
template <typename Enum, std::underlying_type_t<Enum> Val>
  requires std::is_enum<Enum>::value
struct mark_enum : markable_type<Enum, typename std::underlying_type<Enum>::type, Enum>
{
  typedef typename base::representation_type representation_type;
  typedef typename base::storage_type        storage_type;

  static constexpr representation_type marked_value() noexcept { return Val; }
  static constexpr bool is_marked_value(const representation_type& v) noexcept { return v == Val; }

  static constexpr Enum access_value(const storage_type& v) noexcept { return static_cast<Enum>(v); }
  static constexpr storage_type store_value(const Enum& v) noexcept { return static_cast<storage_type>(v); }
};
```

`Enum` is required to be an enumeration type. `Val` a value of integral type, `std::underlying_type_t<Enum>` not necessarily from the range designated by `Enum`.



### Alias template `default_markable`

```c++
template <typename T>
  using default_markable = /* see below */;
```

Type `default_markable<T>` is an alias for `markable<MP(T), order_by_value>`, where `MP(T)`
is a marked-value policy with `value_type` same as `T`.

*Caution:* The library tries to guess whet is the most suitable marked-value policy type `T`.
However, the library may guess incorrectly, so while this is convenient, a safer
usage would be to manually provide the marked-value policy.
